### ISSUE TITLE
Center the buttons under magnify section

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#100]
### Subject of the issue
Center the buttons as shown in the image.
![image](https://user-images.githubusercontent.com/65999534/213881690-c975d561-eea0-4b76-bfed-1c9c2eb05330.png)
Try to make it like this:
![image](https://user-images.githubusercontent.com/65999534/213882346-06fda48b-d97e-47ee-ac69-282f282cdb14.png)
(buttons are 40% of the entire width)

**Comment by papri24majumder** [comment]
I want to work on this issue.

**Comment by developer-diganta** [comment]
Sure. Assigned.

**Comment by papri24majumder** [comment]
![dino-1](https://user-images.githubusercontent.com/101787864/213934192-fc8bf51f-11b1-4705-b33e-1264f248d3d0.jpg)


@developer-diganta sir should the button look like this or

![dino-2](https://user-images.githubusercontent.com/101787864/213934196-36cbbae2-1896-4945-81fc-ceae242023df.jpg)


like this?
