### ISSUE TITLE
Center the buttons in Your Preferences section

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#101]
### Subject of the issue
Center the buttons in the your preferences center.
![image](https://user-images.githubusercontent.com/65999534/213882384-8516e301-7dd5-4b32-bd44-b67283d3e463.png)
You can refer  to issue #100 to see the required widths.

**Comment by Sanya2911** [comment]
I would like to work on this

**Comment by developer-diganta** [comment]
Sure. Go ahead. Assigned.

**Comment by Sanya2911** [comment]
![DINO](https://user-images.githubusercontent.com/120942171/215172114-945f615c-3c54-423b-851a-52d32d955693.jpg)

is this fine?? @developer-diganta

**Comment by developer-diganta** [comment]
Yes!

**Comment by Sanya2911** [comment]
can u please check this PR ?? 
I'm new to GitHub so I don't have much knowledge on how to merge and stuff ... If there is any issue , please guide.
