### ISSUE TITLE
Add a translate option for text on web pages

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#11]
### Subject of the issue
A button can be added to the extension that can help translate selected text to another language. You can take reference from this and embed google translate. 
https://www.w3schools.com/howto/howto_google_translate.asp
If you want to do it in some other way, you're welcome to do that too.

**Comment by Durgesh4993** [comment]
could you assign this work to me

**Comment by developer-diganta** [comment]
Sure!

**Comment by Durgesh4993** [comment]
Thank you for assigning this work.

**Comment by developer-diganta** [comment]
You're welcome

**Comment by Durgesh4993** [comment]
<img width="368" alt="trans1" src="https://user-images.githubusercontent.com/98798977/210238733-53585a59-bec8-4ef5-b536-483fa2e83787.png">

**Comment by Durgesh4993** [comment]
Is being right or not .........

**Comment by Durgesh4993** [comment]
After completing it looks like this

**Comment by developer-diganta** [comment]
Closed via #64
