### ISSUE TITLE
Font style buttons -- Georgia, Times new Roman, Helvatica, Monaco, OpenSans not working

### ISSUE THREAD

**Issue by Srishtihere** [developer-diganta/Dino#110]
### Did you selected this project in SWOC?

Yes

### What happened?

While converting a page's font style, I realized that buttons --- Georgia, Times new Roman, Helvatica, Monaco, OpenSans are not working

### How can we reproduce this bug?

Click on the respective button, the font of the page won't change

### Urgency (Optional)

None

**Comment by developer-diganta** [comment]
Thanks for the issue @Srishtihere ! Assigned.

**Comment by officialarmannqureshi** [comment]
I am interested to fix the bug. Can you assign it to me.

**Comment by developer-diganta** [comment]
Hi @officialarmannqureshi ! @Srishtihere is currently working on it. You can check other issues.

**Comment by Srishtihere** [comment]
@developer-diganta I am unable to work on this issue so, you can assign it to someone else

**Comment by iamatifmoin** [comment]
@developer-diganta Please assign this to me.

**Comment by developer-diganta** [comment]
@iamatifmoin  Yup! Go ahead. Assigned.

**Comment by AnamuddinAhmad** [comment]
@Srishtihere Hey Ma'am is this issue still open ??
