### ISSUE TITLE
Adding a Boot Strap nav Bar to the website

### ISSUE THREAD

**Issue by Harikaraja** [developer-diganta/Dino#114]
Nav Bar is added to the website and a logo followed by project name is displayed on the top left corner of the webiste.

**Comment by developer-diganta** [comment]
For extension, there would be no use  of navbar. But the website for Dino is under development. You can edit that once we have the base code for it.

**Comment by Harikaraja** [comment]
Sir can you tell me any other features or changes that I can add at
present.Please sir...
