### ISSUE TITLE
Changing the font of the logo name

### ISSUE THREAD

**Issue by Neha00011** [developer-diganta/Dino#117]
I want to change the font of heading .Can you please assign this issue to me under SWOC'23?

![Screenshot (56)](https://user-images.githubusercontent.com/112271756/214516190-a832c2b2-ba82-400a-865c-401c8215bd03.png)

**Comment by developer-diganta** [comment]
@Neha00011 Can you please elaborate it a bit more? Since the logo was designed with references to dyslexic friendly fonts, but we can always improve. Do suggest what you are thinking of changing.

**Comment by Neha00011** [comment]
I want to remove! Mark from the name as I think it is little bit weird
looking and also don't size of the heading can be increased a little bit.
It will look better.

**Comment by developer-diganta** [comment]
You can change the size of the header. I have the design files for the logo! I'll change it! Thanks for the suggestion!

**Comment by SonamB11** [comment]
I want to take this issue under SWOC 2023.Please assign this to me.

**Comment by Neha00011** [comment]
Thanks for assigning the issue to me

**Comment by Neha00011** [comment]
Thank you!
