### ISSUE TITLE
 Audio Files are not mapped correctly in the code.

### ISSUE THREAD

**Issue by nerdy-nakul** [developer-diganta/Dino#124]
### Did you selected this project in SWOC?

Yes.
Nakul Singh

### What happened?

What Happened :

When I tap on any of the volume symbols except the introduction one, it should speak what was written on the right of the symbol. But it is speaking something which is in the second or third in the queue. 

Example : When I tap on Your Preferences text to voice symbol it is speaking Font Size. Similarly with all the other symbols.

### How can we reproduce this bug?

You just need to tap on any of the text to voice button except the introduction one.

### Urgency (Optional)

None

**Comment by developer-diganta** [comment]
Thanks @nerdy-nakul ! But can you once again check (with the latest changes)? It seems to be working fine for me.

**Comment by nerdy-nakul** [comment]
Yes, You're right the issue has been solved with the latest changes.
