### ISSUE TITLE
Extention icon is not very visible, missing 16 and 46px icons in manifest.json

### ISSUE THREAD

**Issue by madhav6ram** [developer-diganta/Dino#125]
### Subject of the issue

- The extensions icon is not clearly visible, I propose removing the 'dino' text from the icon, to make it more visible.
- 16px and 48px icons have not been added in manifest.json .

**Comment by madhav6ram** [comment]
Participating in SWOC S3. userid - madhav6ram, discord - Madhav#7781

**Comment by developer-diganta** [comment]
Go ahead! Assigned. Make sure you include the details in the PR template!
