### ISSUE TITLE
Adding text to checkbox in popup header

### ISSUE THREAD

**Issue by madhav6ram** [developer-diganta/Dino#126]
### Subject of the issue
The checkbox in the header of the popup does not have any text, which makes its purpose confusing.

**Comment by madhav6ram** [comment]
Participating in SWOC S3. userid - madhav6ram, discord - Madhav#7781

**Comment by developer-diganta** [comment]
So you want to add like a label to the color scheme toggler right?

**Comment by madhav6ram** [comment]
yes, i think its easily confused as a on/off button without context

**Comment by developer-diganta** [comment]
Sure! Go ahead
