### ISSUE TITLE
Add text to speech functionality

### ISSUE THREAD

**Issue by Durgesh4993** [developer-diganta/Dino#132]
# About Project -
Text-to-speech (TTS) is the ability of your computer to play back written text as spoken words. It help's who don't want to be read the texts..

# Technologies  Used -
HTML, CSS, Javascript etc....

**Comment by Durgesh4993** [comment]
![image](https://user-images.githubusercontent.com/98798977/215269937-433086e5-ff63-45b9-b297-801a53241814.png)

**Comment by developer-diganta** [comment]
Hi @Durgesh4993 ! We currently do not need this functionality since the extension already allows users to read the text from the webpage. Thanks for the suggestion though!
