### ISSUE TITLE
Improve UI of the header

### ISSUE THREAD

**Issue by mohakgupt** [developer-diganta/Dino#137]
### Subject of the issue
I want to change the UI of the header to make it easy to read.
This is what I have made:
![image](https://user-images.githubusercontent.com/100181077/215329940-9249b68d-6c0b-4ad5-99fe-42d717fdae42.png)
Please assign this to me.

**Comment by developer-diganta** [comment]
Let the logo be at the center. For now you can keep the toggle button and the extension's font style changer side by side.

**Comment by mohakgupt** [comment]
Okay, I will make a pr according to that.
