### ISSUE TITLE
Add an option to auto-scroll website

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#15]
### Subject of the issue
Add an option that helps auto-scroll the website. You can add 3 to 5 speeds for auto scroll

**Comment by ManavLohia945** [comment]
I can try working on this issue since I have added the feature of auto-scrolling on one of my websites using JS.

**Comment by developer-diganta** [comment]
Sure

**Comment by ManavLohia945** [comment]
So I should add a button which on clicking the auto-scrolling feature will take place or on a keypress? Suppose user presses the Enter key then the auto-scrolling should happen and when he again presses the Enter key the auto-scrolling should stop..

**Comment by developer-diganta** [comment]
Yeah you can do that. But please don't make any further pr or commits now. Once contribution period starts and you are assigned a project only then start. This is ofcourse if you are in SWOC

**Comment by ManavLohia945** [comment]
Yes I am a participant of SWOC.. Ok so when will the contribution period start?? I thought yesterday the hackathon started and we can start contributing. I have started contributing to 2 other projects and they are accepting PRs..

**Comment by ManavLohia945** [comment]
![image](https://user-images.githubusercontent.com/96055639/210358606-b941b306-0a0d-4d6c-b50e-5109884b6b86.png)
Is this fine I have added this feature below the font size section and when the user presses the enter button the website will auto-scroll and I have considered medium speed.

**Comment by ManavLohia945** [comment]
if you want I can either add a button there with the name auto-scrolling and on clicking that the website will auto-scroll.

**Comment by developer-diganta** [comment]
Make a section (like the font size one) where there will be the options to change auto scroll speed or stop auto scroll.

**Comment by ManavLohia945** [comment]
Ok So I will create a section for auto-scrolling feature above the font size one and provide 3 buttons to control the speed and when the user presses the enter key the auto-scrolling with start and  when he presses again then it will stop. Is this ok ?

**Comment by developer-diganta** [comment]
Yeah!

**Comment by ManavLohia945** [comment]
Hey Diganta!! I have completed this issue sending you the PR now...
