### ISSUE TITLE
Want to add Light and dark mode for websites using Dino.

### ISSUE THREAD

**Issue by officialarmannqureshi** [developer-diganta/Dino#155]
Participant of SWOC:
Username: officialarmannq
Discord:atoz#5954

**Comment by developer-diganta** [comment]
Just to get it clear, you want to add a button that will make websites that do not have a theme toggler, have one right? The dark mode is not for extension right?

**Comment by officialarmannqureshi** [comment]
Yes sir for the current page

**Comment by developer-diganta** [comment]
Cool! Go ahead! Do ask if you need any help!
