### ISSUE TITLE
Add English Dictionary

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#16]
### Subject of the issue
Add a feature that allows users to select a word from the webpage and then it gives back its dictionary meaning.

**Comment by vijay-kumar-yadav** [comment]
Please assign this issue to me.

**Comment by vijay-kumar-yadav** [comment]
which code formatter you have used?? @developer-diganta

**Comment by developer-diganta** [comment]
@vijay-kumar-yadav I have not exclusively used any formatter yet. Just the default HTML formatter from VSCode

**Comment by vijay-kumar-yadav** [comment]
@developer-diganta  check my pr

**Comment by vijay-kumar-yadav** [comment]
@developer-diganta  
see this repo [https://github.com/Kumar-laxmi/Algorithms](url) it is also in swoc they have started taking PR.

**Comment by developer-diganta** [comment]
We have got the forms! No problems now! I'll start merging the PRs soon!
