### ISSUE TITLE
🧑‍💻 Add Contributors and Admin Details

### ISSUE THREAD

**Issue by Suryansh1720001** [developer-diganta/Dino#162]
Hello @developer-diganta 

#### In README FILE
🧑‍💻 Add Contributors and Admin Details with extra info 

**Is your feature request related to a problem? Please describe.**
### Features that I want to add

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive

**Describe the solution you'd like**

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by developer-diganta** [comment]
Assigned!

**Comment by Durgesh4993** [comment]
Hello @Suryansh1720001 before starting please check out My PR because i have already added Admin Details in Readme File

**Comment by Durgesh4993** [comment]
And also i'll changed some features on Readme File

**Comment by Suryansh1720001** [comment]
@Durgesh4993 
Okay I will keep this in mind
