### ISSUE TITLE
Create A Web Page Mockup for Dino

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#2]
### Subject of the issue
Since Dino is a chrome extension, it would be great to have a webpage dedicated to it. We'll host it via GitHub pages.

### Your environment
N.A.

### Steps to reproduce
N.A.

### Expected behaviour
N.A.

### Actual behaviour
N.A.

**Comment by ManavLohia945** [comment]
Hey bro !! I came across this project through Social Winter of Code and it really intrigued me and I wish to contribute to this issue can you guide me like how this whole process will be...

**Comment by developer-diganta** [comment]
Sure! What the main aim is to create a web page that will contain the chrome extension as a downloadable file. Sections like about, examples etc can also be kept. If you want you can simply give a mock up of the website using Figma as well and we can then decide before you get to coding. And I'll soon add a contributing readme to guide about the contribution process.

**Comment by ManavLohia945** [comment]
ya sounds good. I also have a friend actually who has participated in this event and he is more into UI/UX part so is it ok if he and I together create the mock up and then I will get the coding part done during the event time...

**Comment by developer-diganta** [comment]
Sounds great!

**Comment by ManavLohia945** [comment]
ok great We will start working on designing the mock up and you can always provide us with your input and suggestions on that!!

**Comment by developer-diganta** [comment]
Sure!

**Comment by Durgesh4993** [comment]
Sir can i re degine the web page of Dino , please aassign me this work

**Comment by developer-diganta** [comment]
Thanks @Durgesh4993 for the interest. But presently @ManavLohia945 is already working on it.

**Comment by Durgesh4993** [comment]
ok sir

**Comment by ManavLohia945** [comment]
Sure bro I was going to ask you regarding this.
Works for me.

**Comment by developer-diganta** [comment]
Yeah! If I receive any other guidelines, I'll let you all know! And regarding the website, just make it a simple one. We can then better it by adding more issues!

**Comment by ManavLohia945** [comment]
Ya no problem we have designed some sections of  the main page will share
with you soon..

**Comment by Ujwal19k** [comment]
Hi Diganta, I have created some sections of the UI for the webpage of Dino and mailed you the figma file you can assign me this issue and I will continue working on the remaining sections

**Comment by developer-diganta** [comment]
Ujwal does one thing, no need to create about us, contact us in this issue
itself. Till now whatever you have done, share that in the issue, and I'll
make a new folder where you can upload the screenshots. For us etc, I'll
make a new issue and assign it to you.

**Comment by ManavLohia945** [comment]
So You are creating a new issue for the coding part right ? I don’t have to create one ?

**Comment by developer-diganta** [comment]
Yeah I'll create it. Let @Ujwal19k  make a PR and I'll make an issue tagging that PR.

**Comment by developer-diganta** [comment]
@Ujwal19k I have made the folder. You can upload your screenshots there

**Comment by ManavLohia945** [comment]
Ya No problem works for us. He will update the remaining sections and send you the PR within 1hr..

**Comment by Ujwal19k** [comment]
I have sent you the PR. I am working on improving the UI for the sections.

**Comment by developer-diganta** [comment]
Closed via #23
