### ISSUE TITLE
Add Stop speaking button

### ISSUE THREAD

**Issue by Rahulj9a** [developer-diganta/Dino#26]
### Subject of the issue
Once the page start speak there is no way to stop it

### Your environment
* Chrome

### Steps to reproduce
Add a stop button 

### Expected behaviour
User should be able to stop page to speak

### Actual behaviour
Unable to stop speaking

**Comment by Rahulj9a** [comment]
I want to contribute in this issue, can it be assigned to me

**Comment by developer-diganta** [comment]
Thank You for the issue! Assigned!

**Comment by Rahulj9a** [comment]
https://github.com/developer-diganta/Dino/pull/49#issue-1520092090
PR is sent, kindly review it

**Comment by developer-diganta** [comment]
Closed via #52
