### ISSUE TITLE
Remove Unnecessary Comments

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#4]
### Subject of the issue
Remove unnecessary comments from different files.

**Comment by Durgesh4993** [comment]
Hello sir, could you assign this work to me

**Comment by developer-diganta** [comment]
Sure!

**Comment by Shubhodaya** [comment]
Hello sir can I work on it for swoc ?

**Comment by developer-diganta** [comment]
@Shubhodaya Thank You for your interest! But presently @Durgesh4993 is already working on it. You can pick other issues if you want!

**Comment by Durgesh4993** [comment]
sir, i will remove comments it right or wrong, could you verify code

**Comment by developer-diganta** [comment]
Closed as completed by #10
