### ISSUE TITLE
Fixed the typography error by correcting the listen spelling

### ISSUE THREAD

**Issue by Shubh08am** [developer-diganta/Dino#44]
- **Initial Display:-** 

![image](https://user-images.githubusercontent.com/83953214/210629541-a5a23f25-82e9-45b8-ae70-09b1992b6c42.png)

![image](https://user-images.githubusercontent.com/83953214/210629468-ccd13475-3710-4a96-8734-11eec6edcb35.png)

- **Corrected Display:-**

![image](https://user-images.githubusercontent.com/83953214/210630408-cb45495d-191b-4a3e-9377-a67fd93e7f92.png)

![image](https://user-images.githubusercontent.com/83953214/210630282-363a681f-80a0-4987-9c88-b47af1630bfc.png)

**Comment by developer-diganta** [comment]
Closed via #45
