### ISSUE TITLE
Add different color for color blind people

### ISSUE THREAD

**Issue by papri24majumder** [developer-diganta/Dino#48]
As mentioned, the Dino chrome extension is for both dyslexia and color-blind people. So, I want to add different colors for color-blind people to highlight links, paragraphs, and background colors.
![image](https://user-images.githubusercontent.com/101787864/210706028-61334a1a-35f0-45fa-9811-458689f891f2.png)

**Comment by developer-diganta** [comment]
Cool! This would be really helpful. Go ahead

**Comment by papri24majumder** [comment]
@developer-diganta sir when I am changing the link highlight color from yellow to any other color, the links in the website still get highlighted by yellow. Can you please explain why it's happening?
![i1](https://user-images.githubusercontent.com/101787864/211289601-51c19219-df24-4610-8cb1-d42560ac11fb.jpg)
![i2](https://user-images.githubusercontent.com/101787864/211289615-12353e40-734e-46cc-977f-89effa55db8a.jpg)

**Comment by developer-diganta** [comment]
Hi @papri24majumder ! Just make a PR so that I can see the entire code once. Helps to debug.

**Comment by papri24majumder** [comment]
Ok sir I will try that
