### ISSUE TITLE
Starter code for website of Dino

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#59]
### Subject of the issue
Construct the code for the website as per the design mockup.

Prefer HTML,CSS and JS rather than any framework (up for discussion if you want)

**Comment by DHRUVKHANDELWAL00** [comment]
@developer-diganta  Can i try it?

**Comment by ManavLohia945** [comment]
Sorry @DHRUVKHANDELWAL00 . I have been discussing about this issue with @developer-diganta even before when SWOC started, So he is going to assign me this work. I have been looking forward to work on this issue for quite some time. So, I am sorry but you can look out for other issues

**Comment by DHRUVKHANDELWAL00** [comment]
Okay manav. Also No need to say sorry @ManavLohia945 .

**Comment by developer-diganta** [comment]
Thanks @DHRUVKHANDELWAL00 for understanding! @ManavLohia945 assigned

**Comment by ManavLohia945** [comment]
Hey diganta !! Just wanted to update you regarding this issue I am done with the front end part only the javascript part is remaining. I am creating a PR related to this issue so that you can have a look at the work I am done with..
