### ISSUE TITLE
Improve Issue template

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#6]
### Subject of the issue
Improve Issue template and add more options

**Comment by SattyamSamania** [comment]
> ### Subject of the issue
> Improve Issue template and add more options
> 
> 

Hey @developer-diganta Can you assign me this issue and tell further what to do next

**Comment by developer-diganta** [comment]
Sure! You can find the template files here https://github.com/developer-diganta/Dino/tree/main/.github/ISSUE_TEMPLATE. 
You can make them as bug, enhancement, website in three files and add requisites for the same inside them (just like current ones). If you need help do let me know! And do not worry about these requisites though, if needed I'll modify them.

**Comment by SattyamSamania** [comment]
> Sure! You can find the template files here https://github.com/developer-diganta/Dino/tree/main/.github/ISSUE_TEMPLATE. You can make them as bug, enhancement, website in three files and add requisites for the same inside them (just like current ones). If you need help do let me know! And do not worry about these requisites though, if needed I'll modify them.

@developer-diganta Thanks for the suggestions. so if i have to add some enhancement  should I add in the existing two files or should I create new ones with new features like we can ask for screenshots or some questions like  Describe your solution etc..

**Comment by developer-diganta** [comment]
It would be better if you create new ones (or rename the existing two and add a third one). Whatever you feel like!

**Comment by SattyamSamania** [comment]
> It would be better if you create new ones (or rename the existing two and add a third one). Whatever you feel like! But work on it during the contribution period of SWOC after you have selected this project.

@developer-diganta Yes I have selected this project and don't know about when the contribution period will start. And I am adding 2 templates one for feature request and another for Bug and i will create a draft pull request so you can check and after that will create proper PR.

**Comment by SattyamSamania** [comment]
> > It would be better if you create new ones (or rename the existing two and add a third one). Whatever you feel like! But work on it during the contribution period of SWOC after you have selected this project.
> 
> @developer-diganta Yes I have selected this project and don't know about when the contribution period will start. And I am adding 2 templates one for feature request and another for Bug and i will create a draft pull request so you can check and after that will create proper PR.

@developer-diganta And I am creating the yaml files instead of Readme. You can check after I make a Draft PR.
