### ISSUE TITLE
Add reader option

### ISSUE THREAD

**Issue by vijay-kumar-yadav** [developer-diganta/Dino#61]
![image](https://user-images.githubusercontent.com/83089894/211149977-44fe8845-680f-4368-8f93-6ccbb8cb6494.png)

Like in microsoft forms if user clicks on the button it will read adjacent text for them. Making it lot easier for them to work with extension.

Assign me this don't worry about icon I will add icon so that it has a transparent background and matching with the theme.

Microsoft form example:
![image](https://user-images.githubusercontent.com/83089894/211150208-28077669-ea52-46de-9020-66d927dec47c.png)

**Comment by developer-diganta** [comment]
Cool addition! This would be really helpful! Go ahead @vijay-kumar-yadav

**Comment by vijay-kumar-yadav** [comment]
@developer-diganta please review PR.
