### ISSUE TITLE
Add a loader while dictionary loads

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#63]
### Subject of the issue
After selecting a word, when we click on the Get Definition button there is a delay due to API call. Try to add a small loader or an appropriate waiting message while the meaning is being fetched.

![image](https://user-images.githubusercontent.com/65999534/211167210-4da802b0-310a-49cb-af47-2881c6342d65.png)

**Comment by BhagatHarsh** [comment]
I would like to work on this issue.

**Comment by developer-diganta** [comment]
Sure! Go ahead.

**Comment by developer-diganta** [comment]
Closed via #65
