### ISSUE TITLE
add convert to lowercase button

### ISSUE THREAD

**Issue by Mridul-2003** [developer-diganta/Dino#69]
### Subject of the issue
Describe your issue here.

### Your environment
* version of angular-translate
* version of angular
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by Mridul-2003** [comment]
plz assign me this issue

**Comment by developer-diganta** [comment]
Thank you @Mridul-2003 . But people with dyslexia may find it hard to read capital letters. You can instead change this to the opposite one i.e. the caps to lowercase. You can refer to this article: https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide#:~:text=Avoid%20using%20all%20capital%20letters,letters%20are%20easier%20to%20read.

**Comment by Mridul-2003** [comment]
ok i add button for lowercase.Thanks for assign this to me
