### ISSUE TITLE
Add custom scroll bar

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#7]
### Subject of the issue
Make the scroll bar custom
![image](https://user-images.githubusercontent.com/65999534/210038720-37edcc5f-f867-4f3f-8743-4b650dfd1ef7.png)

**Comment by daredevil3435** [comment]
Hey, I want to work on this issue. Please assign this issue to me

**Comment by developer-diganta** [comment]
Yeah sure! Go ahead!

**Comment by daredevil3435** [comment]
@developer-diganta can you confirm if scrollbar i added is fine?

**Comment by developer-diganta** [comment]
Great work! The scroll bar looks great! I'll wait till the contributing period and then merge it.

**Comment by daredevil3435** [comment]
Yup, thanks!

**Comment by developer-diganta** [comment]
Closed as complete

**Comment by daredevil3435** [comment]
thank you!! I am happy as my first contribution is complete now.

**Comment by developer-diganta** [comment]
Cool! The first contribution always feels great!
