### ISSUE TITLE
Correct popup.html

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#70]
### Subject of the issue
popup.html due to some changes, shows the same content twice. This needs to be corrected.

**Comment by Durgesh4993** [comment]
can i do this work

**Comment by Durgesh4993** [comment]
please assign this work to me sir

**Comment by developer-diganta** [comment]
Go ahead

**Comment by amajaying** [comment]
This issue was occurring because the HTML code was copied twice in the "popup.html". Can be solved just by deleting the duplicate code. @Durgesh4993 if you're not working on this, let me know, I'll raise the PR.
