### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by AnishDubey27** [developer-diganta/Dino#73]
### Subject of the issue
Modification of CONTRIBUTING.md

### Problem Statement:
There are many first time contributors who might be unable to use the terminal efficiently.

### Solution:
We can make some changes in the CONTRIBUTING.md file and add a step by step process how a person can contribute to the project with the help of GITHUB DESKTOP application, without the need to write a single command manually.

I would like to work on the same issue.

**Comment by developer-diganta** [comment]
That would really be helpful. Go ahead. Also add the link of contributing.md in readme.md. Assigned.
