### ISSUE TITLE
Color of Sliders.

### ISSUE THREAD

**Issue by Vatsalmadhur** [developer-diganta/Dino#75]
### Subject of the issue
When turning on the extension,the background color goes blue which contradicts the slider color present in the 'Rate' and 'Magnifier' section.

### Your environment
* version of angular-translate
* version of angular
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by Vatsalmadhur** [comment]
Please assign me this issue.

**Comment by developer-diganta** [comment]
Sure! Go ahead
