### ISSUE TITLE
Position of '+' and '-' buttons.

### ISSUE THREAD

**Issue by Vatsalmadhur** [developer-diganta/Dino#76]
<img width="624" alt="Screenshot 2023-01-12 at 8 04 56 PM" src="https://user-images.githubusercontent.com/107473447/212094630-7e5789e6-3c01-4050-be4a-8a3c48403452.png">
### Subject of the issue

In the Magnifier section,i suggest to make the '+' button towards the right side and '-' on the left as generally people assume its this way only.

### Your environment
* version of angular-translate
* version of angular
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by Vatsalmadhur** [comment]
I request you to please assign me this issue.

**Comment by developer-diganta** [comment]
Sure. Go ahead

**Comment by AmanDeva** [comment]
Please sir assign me this issue.

**Comment by developer-diganta** [comment]
@Vatsalmadhur Are you still working on this?

**Comment by Vatsalmadhur** [comment]
Yes sir i am working. Actually due to university exams i am unable to make a PR. In a couple of days i will surely complete it .

**Comment by thenamannanda** [comment]
Hi, would you assign me this issue if its still open?
