### ISSUE TITLE
Add a option to change underlines and italics to bold.

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#77]
### Subject of the issue
https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide#:~:text=Use%20sans%20serif%20fonts%2C%20such,may%20request%20a%20larger%20font.
You can find from this article that it is better to avoid using italics and underlines to produce a dyslexic friendly web page. So we can add an option that would allow italics and underlines to be converted to bold.
I guess we can have 3 buttons in this section, one which changes the italics to bolds and one which changes underlines to bolds. The third button could revert the action. So you also have to store which were italics and which were bold.

**Comment by 07Apollo07** [comment]
I would like to work on this issue

**Comment by Shruti0316** [comment]
@developer-diganta I would like to work in this issue. Can you please assign it to me.

**Comment by Shruti0316** [comment]
Sure, I'll contribute via other issues

**Comment by developer-diganta** [comment]
Thanks @Shruti0316 ! @07Apollo07 assigned!
