### ISSUE TITLE
Add an option to select type of highlight for links

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#81]
### Subject of the issue
Currently the link highlighter only adds a background to highlight links. We can have 2 options:
1. Add border to link
2. Add background to links(the current behavior)
Feel free to ask any question.

**Comment by 07Apollo07** [comment]
@developer-diganta  I would like to work on this issue

**Comment by developer-diganta** [comment]
Sure. Go ahead. Assigned.
