### ISSUE TITLE
Add an option to save preferences in local storage

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/Dino#82]
### Subject of the issue
The user can have an option to save the preferences that he/she has used. This can be done using localStorage. Feel free to discuss the approach if you want to contribute to this issue.

**Comment by Rahulj9a** [comment]
So we can make a button that take present values of each option and then store it in local storage and an another button that can fetch these values from storage and apply on the options, is this approach is ok?.

**Comment by Rahulj9a** [comment]
Can you assign it to me,

**Comment by developer-diganta** [comment]
Yup something on that lines. What you can do is keep a toggle check. If it is set to true, keep the track of options selected and keep storing it in the localStorage. Also have one option to set the old settings to web page. Upon toggling that, the webpage should take the previous settings if any. Do ask if you have any doubts.

**Comment by Rahulj9a** [comment]
Regarding toggle button: I have tried some approach but all failed, So can you help me. 1.) one was to store old settings in content.js and then create an action that will apply that old settings. but to doing so we have to declare variables globally and that will change almost whole content.js, 2.) we keep track of old settings which are changed by user, but that will create issue that if we toggle to old settings than some of settings will remain according to local storage preferences (settings which are not changed by user). like:- a user store: fontStyle:x, and fontSize:2; it goes on second website and there just change fontStyle and then trigger stored changes, and then when he try to undo those changes only fontStyle will change fontSize will remain according to stored preferences
