### ISSUE TITLE
I want to add Tahoma font-face 

### ISSUE THREAD

**Issue by officialarmannqureshi** [developer-diganta/Dino#95]
#  **Description**
For people with dyslexia ,Tahoma font is the best readable font for people having a dyslexia disorder along with this  also due to enough spacing between letters. Therefore ,I want to add Tahoma Font to your project.

# Screenshot

<img width="952" alt="Issue-1" src="https://user-images.githubusercontent.com/91754196/213436419-c766bc85-dd10-4339-b701-a0aa2d496c7a.png">

# Types of changes
- [x]  New feature added
- [ ]  Bug fix
- [ ]  Breaking change 

# SWOC PARTICIPANT
- Name : Mohammad Nazim Qureshi
* Discord : atoz #5954
+ Devfolio username :officialarmannq

**Comment by developer-diganta** [comment]
Sure. Go ahead. Assigned.
